#include "all.h"

namespace dvl {

/** Data related to each spell ID. */
SpellData spelldata[] = {
	// clang-format off
	// sName,    sManaCost, sType,           sNameText,         sSkillText, sBookLvl, sStaffLvl, sTargeted, sTownSpell, sMinInt, sSFX,     sMissiles[3],                         sManaAdj, sMinMana, sStaffMin, sStaffMax, sBookCost, sStaffCost
	{ SpellId::none,          0, 0,               NULL,              NULL,              0,         0, false,     false,            0, 0,        { 0,                 0,          0 },        0,        0,        40,        80,         0,          0 },
	{ SpellId::FIREBOLT,      6, MagicType::FIRE,      "Firebolt",        "Firebolt",        1,         1, true,      false,           15, IS_CAST2, { MissileType::FIREBOLT,      0,          0 },        1,        3,        40,        80,      1000,         50 },
	{ SpellId::HEAL,          5, MagicType::MAGIC,     "Healing",         NULL,              1,         1, false,     true,            17, IS_CAST8, { MissileType::HEAL,          0,          0 },        3,        1,        20,        40,      1000,         50 },
	{ SpellId::LIGHTNING,    10, MagicType::LIGHTNING, "Lightning",       NULL,              4,         3, true,      false,           20, IS_CAST4, { MissileType::LIGHTCTRL,     0,          0 },        1,        6,        20,        60,      3000,        150 },
	{ SpellId::FLASH,        30, MagicType::LIGHTNING, "Flash",           NULL,              5,         4, false,     false,           33, IS_CAST4, { MissileType::FLASH,         MissileType::FLASH2, 0 },        2,       16,        20,        40,      7500,        500 },
	{ SpellId::IDENTIFY,     13, MagicType::MAGIC,     "Identify",        "Identify",       -1,        -1, false,     true,            23, IS_CAST6, { MissileType::IDENTIFY,      0,          0 },        2,        1,         8,        12,         0,        100 },
	{ SpellId::FIREWALL,     28, MagicType::FIRE,      "Fire Wall",       NULL,              3,         2, true,      false,           27, IS_CAST2, { MissileType::FIREWALLC,     0,          0 },        2,       16,         8,        16,      6000,        400 },
	{ SpellId::TOWN,         35, MagicType::MAGIC,     "Town Portal",     NULL,              3,         3, true,      false,           20, IS_CAST6, { MissileType::TOWN,          0,          0 },        3,       18,         8,        12,      3000,        200 },
	{ SpellId::STONE,        60, MagicType::MAGIC,     "Stone Curse",     NULL,              6,         5, true,      false,           51, IS_CAST2, { MissileType::STONE,         0,          0 },        3,       40,         8,        16,     12000,        800 },
	{ SpellId::INFRA,        40, MagicType::MAGIC,     "Infravision",     NULL,             -1,        -1, false,     false,           36, IS_CAST8, { MissileType::INFRA,         0,          0 },        5,       20,         0,         0,         0,        600 },
	{ SpellId::RNDTELEPORT,  12, MagicType::MAGIC,     "Phasing",         NULL,              7,         6, false,     false,           39, IS_CAST2, { MissileType::RNDTELEPORT,   0,          0 },        2,        4,        40,        80,      3500,        200 },
	{ SpellId::MANASHIELD,   33, MagicType::MAGIC,     "Mana Shield",     NULL,              6,         5, false,     false,           25, IS_CAST2, { MissileType::MANASHIELD,    0,          0 },        0,       33,         4,        10,     16000,       1200 },
	{ SpellId::FIREBALL,     16, MagicType::FIRE,      "Fireball",        NULL,              8,         7, true,      false,           48, IS_CAST2, { MissileType::FIREBALL,      0,          0 },        1,       10,        40,        80,      8000,        300 },
	{ SpellId::GUARDIAN,     50, MagicType::FIRE,      "Guardian",        NULL,              9,         8, true,      false,           61, IS_CAST2, { MissileType::GUARDIAN,      0,          0 },        2,       30,        16,        32,     14000,        950 },
	{ SpellId::CHAIN,        30, MagicType::LIGHTNING, "Chain Lightning", NULL,              8,         7, false,     false,           54, IS_CAST2, { MissileType::CHAIN,         0,          0 },        1,       18,        20,        60,     11000,        750 },
	{ SpellId::WAVE,         35, MagicType::FIRE,      "Flame Wave",      NULL,              9,         8, true,      false,           54, IS_CAST2, { MissileType::WAVE,          0,          0 },        3,       20,        20,        40,     10000,        650 },
	{ SpellId::DOOMSERP,      0, MagicType::LIGHTNING, "Doom Serpents",   NULL,             -1,        -1, false,     false,            0, IS_CAST2, { 0,                 0,          0 },        0,        0,        40,        80,         0,          0 },
	{ SpellId::BLODRIT,       0, MagicType::MAGIC,     "Blood Ritual",    NULL,             -1,        -1, false,     false,            0, IS_CAST2, { 0,                 0,          0 },        0,        0,        40,        80,         0,          0 },
	{ SpellId::NOVA,         60, MagicType::MAGIC,     "Nova",            NULL,             -1,        10, false,     false,           87, IS_CAST4, { MissileType::NOVA,          0,          0 },        3,       35,        16,        32,     21000,       1300 },
	{ SpellId::INVISIBIL,     0, MagicType::MAGIC,     "Invisibility",    NULL,             -1,        -1, false,     false,            0, IS_CAST2, { 0,                 0,          0 },        0,        0,        40,        80,         0,          0 },
	{ SpellId::FLAME,        11, MagicType::FIRE,      "Inferno",         NULL,              3,         2, true,      false,           20, IS_CAST2, { MissileType::FLAMEC,        0,          0 },        1,        6,        20,        40,      2000,        100 },
	{ SpellId::GOLEM,       100, MagicType::FIRE,      "Golem",           NULL,             11,         9, false,     false,           81, IS_CAST2, { MissileType::GOLEM,         0,          0 },        6,       60,        16,        32,     18000,       1100 },
	{ SpellId::BLODBOIL,      0, MagicType::LIGHTNING, "Blood Boil",      NULL,             -1,        -1, true,      false,            0, IS_CAST8, { 0,                 0,          0 },        0,        0,         0,         0,         0,          0 },
	{ SpellId::TELEPORT,     35, MagicType::MAGIC,     "Teleport",        NULL,             14,        12, true,      false,          105, IS_CAST6, { MissileType::TELEPORT,      0,          0 },        3,       15,        16,        32,     20000,       1250 },
	{ SpellId::APOCA,       150, MagicType::FIRE,      "Apocalypse",      NULL,             -1,        15, false,     false,          149, IS_CAST2, { MissileType::APOCA,         0,          0 },        6,       90,         8,        12,     30000,       2000 },
	{ SpellId::ETHEREALIZE, 100, MagicType::MAGIC,     "Etherealize",     NULL,             -1,        -1, false,     false,           93, IS_CAST2, { MissileType::ETHEREALIZE,   0,          0 },        0,      100,         2,         6,     26000,       1600 },
	{ SpellId::REPAIR,        0, MagicType::MAGIC,     "Item Repair",     "Item Repair",    -1,        -1, false,     true,            -1, IS_CAST6, { MissileType::REPAIR,        0,          0 },        0,        0,        40,        80,         0,          0 },
	{ SpellId::RECHARGE,      0, MagicType::MAGIC,     "Staff Recharge",  "Staff Recharge", -1,        -1, false,     true,            -1, IS_CAST6, { MissileType::RECHARGE,      0,          0 },        0,        0,        40,        80,         0,          0 },
	{ SpellId::DISARM,        0, MagicType::MAGIC,     "Trap Disarm",     "Trap Disarm",    -1,        -1, false,     false,           -1, IS_CAST6, { MissileType::DISARM,        0,          0 },        0,        0,        40,        80,         0,          0 },
	{ SpellId::ELEMENT,      35, MagicType::FIRE,      "Elemental",       NULL,              8,         6, false,     false,           68, IS_CAST2, { MissileType::ELEMENT,       0,          0 },        2,       20,        20,        60,     10500,        700 },
	{ SpellId::CBOLT,         6, MagicType::LIGHTNING, "Charged Bolt",    NULL,              1,         1, true,      false,           25, IS_CAST2, { MissileType::CBOLT,         0,          0 },        1,        6,        40,        80,      1000,         50 },
	{ SpellId::HBOLT,         7, MagicType::MAGIC,     "Holy Bolt",       NULL,              1,         1, true,      false,           20, IS_CAST2, { MissileType::HBOLT,         0,          0 },        1,        3,        40,        80,      1000,         50 },
	{ SpellId::RESURRECT,    20, MagicType::MAGIC,     "Resurrect",       NULL,             -1,         5, false,     true,            30, IS_CAST8, { MissileType::RESURRECT,     0,          0 },        0,       20,         4,        10,      4000,        250 },
	{ SpellId::TELEKINESIS,  15, MagicType::MAGIC,     "Telekinesis",     NULL,              2,         2, false,     false,           33, IS_CAST2, { MissileType::TELEKINESIS,   0,          0 },        2,        8,        20,        40,      2500,        200 },
	{ SpellId::HEALOTHER,     5, MagicType::MAGIC,     "Heal Other",      NULL,              1,         1, false,     true,            17, IS_CAST8, { MissileType::HEALOTHER,     0,          0 },        3,        1,        20,        40,      1000,         50 },
	{ SpellId::FLARE,        25, MagicType::MAGIC,     "Blood Star",      NULL,             14,        13, false,     false,           70, IS_CAST2, { MissileType::FLARE,         0,          0 },        2,       14,        20,        60,     27500,       1800 },
	{ SpellId::BONESPIRIT,   24, MagicType::MAGIC,     "Bone Spirit",     NULL,              9,         7, false,     false,           34, IS_CAST2, { MissileType::BONESPIRIT,    0,          0 },        1,       12,        20,        60,     11500,        800 },
	// clang-format on
};

}
