#include "all.h"

DEVILUTION_BEGIN_NAMESPACE

/** Maps from dun_object_id to object_id. */
int ObjTypeConv[] = {
	ObjectType::L1LIGHT,
	ObjectType::LEVER,
	ObjectType::CRUX1,
	ObjectType::CRUX2,
	ObjectType::CRUX3,
	ObjectType::ANGEL,
	ObjectType::BANNERL,
	ObjectType::BANNERM,
	ObjectType::BANNERR,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::BOOK2L,
	ObjectType::BOOK2R,
	ObjectType::BCROSS,
	ObjectType::L1LIGHT,
	ObjectType::CANDLE1,
	ObjectType::CANDLE2,
	ObjectType::CANDLEO,
	ObjectType::CAULDRON,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::FLAMEHOLE,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::MCIRCLE1,
	ObjectType::MCIRCLE2,
	ObjectType::SKFIRE,
	ObjectType::SKPILE,
	ObjectType::SKSTICK1,
	ObjectType::SKSTICK2,
	ObjectType::SKSTICK3,
	ObjectType::SKSTICK4,
	ObjectType::SKSTICK5,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::SWITCHSKL,
	ObjectType::L1LIGHT,
	ObjectType::TRAPL,
	ObjectType::TRAPR,
	ObjectType::TORTURE1,
	ObjectType::TORTURE2,
	ObjectType::TORTURE3,
	ObjectType::TORTURE4,
	ObjectType::TORTURE5,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::NUDEW2R,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::TNUDEM1,
	ObjectType::TNUDEM2,
	ObjectType::TNUDEM3,
	ObjectType::TNUDEM4,
	ObjectType::TNUDEW1,
	ObjectType::TNUDEW2,
	ObjectType::TNUDEW3,
	ObjectType::CHEST1,
	ObjectType::CHEST1,
	ObjectType::CHEST1,
	ObjectType::CHEST2,
	ObjectType::CHEST2,
	ObjectType::CHEST2,
	ObjectType::CHEST3,
	ObjectType::CHEST3,
	ObjectType::CHEST3,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::PEDISTAL,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::ALTBOY,
	ObjectType::L1LIGHT,
	ObjectType::L1LIGHT,
	ObjectType::WARARMOR,
	ObjectType::WARWEAP,
	ObjectType::TORCHR2,
	ObjectType::TORCHL2,
	ObjectType::MUSHPATCH,
	ObjectType::STAND,
	ObjectType::TORCHL,
	ObjectType::TORCHR,
	ObjectType::FLAMELVR,
	ObjectType::SARC,
	ObjectType::BARREL,
	ObjectType::BARRELEX,
	ObjectType::BOOKSHELF,
	ObjectType::BOOKCASEL,
	ObjectType::BOOKCASER,
	ObjectType::ARMORSTAND,
	ObjectType::ARMORSTANDN,
	ObjectType::WEAPONRACK,
	ObjectType::WEAPONRACKN,
	ObjectType::SLAINHERO,
	ObjectType::WATER,
	ObjectType::BLOODFTN,
	ObjectType::PURIFYINGFTN,
	ObjectType::SHRINEL,
	ObjectType::SHRINER,
	ObjectType::GOATSHRINE,
	ObjectType::MURKYFTN,
	ObjectType::TEARFTN,
	ObjectType::DECAP,
	ObjectType::TCHEST2,
	ObjectType::STORYBOOK,
	ObjectType::L1LDOOR,
	ObjectType::L1RDOOR,
	ObjectType::L2LDOOR,
	ObjectType::L2RDOOR,
	ObjectType::L3LDOOR,
	ObjectType::L3RDOOR,
	ObjectType::BLINDBOOK,
	ObjectType::BLOODBOOK,
	ObjectType::LAZSTAND,
};

/** Contains the data related to each object ID. */
ObjDataStruct AllObjects[99] = {
	// clang-format off
	// oload, ofindex,   ominlvl, omaxlvl, olvltype,        otheme,                  oquest,     oAnimFlag, oAnimDelay, oAnimLen, oAnimWidth, oSolidFlag, oMissFlag, oLightFlag, oBreak, oSelFlag, oTrapFlag
	{      1, ObjectGraphic::L1BRAZ,    1,       4, DunType::cathedral, THEME_NONE,              -1,                 1,          1,       26,         64, true,       true,      false,           0,        0, false     },
	{      1, ObjectGraphic::L1DOORS,   1,       4, DunType::cathedral, THEME_NONE,              -1,                 0,          1,        0,         64, false,      false,     true,            0,        3, true      },
	{      1, ObjectGraphic::L1DOORS,   1,       4, DunType::cathedral, THEME_NONE,              -1,                 0,          2,        0,         64, false,      false,     true,            0,        3, true      },
	{      3, ObjectGraphic::SKULFIRE,  0,       0, DunType::town,      THEME_SKELROOM,          -1,                 1,          2,       11,         96, true,       true,      false,           0,        0, false     },
	{      1, ObjectGraphic::LEVER,     1,       4, DunType::cathedral, THEME_NONE,              -1,                 0,          1,        1,         96, true,       true,      true,            0,        1, true      },
	{      1, ObjectGraphic::CHEST1,    1,      16, DunType::town,      THEME_NONE,              -1,                 0,          1,        0,         96, true,       true,      true,            0,        1, true      },
	{      1, ObjectGraphic::CHEST2,    1,      16, DunType::town,      THEME_NONE,              -1,                 0,          1,        0,         96, true,       true,      true,            0,        1, true      },
	{      1, ObjectGraphic::CHEST3,    1,      16, DunType::town,      THEME_NONE,              -1,                 0,          1,        0,         96, true,       true,      true,            0,        1, true      },
	{      2, ObjectGraphic::L1BRAZ,    0,       0, DunType::town,      THEME_NONE,              -1,                 0,          0,        0,          0, false,      false,     false,           0,        0, false     },
	{      3, ObjectGraphic::CANDLE2,   0,       0, DunType::town,      THEME_SHRINE,            -1,                 1,          2,        4,         96, true,       true,      true,            0,        0, false     },
	{      2, ObjectGraphic::L1BRAZ,    0,       0, DunType::town,      THEME_NONE,              -1,                 0,          0,        0,          0, false,      false,     false,           0,        0, false     },
	{      3, ObjectGraphic::BANNER,    0,       0, DunType::town,      THEME_SKELROOM,          -1,                 0,          2,        0,         96, true,       true,      true,            0,        0, false     },
	{      3, ObjectGraphic::BANNER,    0,       0, DunType::town,      THEME_SKELROOM,          -1,                 0,          1,        0,         96, true,       true,      true,            0,        0, false     },
	{      3, ObjectGraphic::BANNER,    0,       0, DunType::town,      THEME_SKELROOM,          -1,                 0,          3,        0,         96, true,       true,      true,            0,        0, false     },
	{      2, ObjectGraphic::SKULPILE,  1,       4, DunType::town,      THEME_NONE,              -1,                 0,          0,        1,         96, true,       true,      true,            0,        0, false     },
	{      2, ObjectGraphic::L1BRAZ,    0,       0, DunType::town,      THEME_NONE,              -1,                 0,          0,        0,          0, false,      false,     false,           0,        0, false     },
	{      2, ObjectGraphic::L1BRAZ,    0,       0, DunType::town,      THEME_NONE,              -1,                 0,          0,        0,          0, false,      false,     false,           0,        0, false     },
	{      2, ObjectGraphic::L1BRAZ,    0,       0, DunType::town,      THEME_NONE,              -1,                 0,          0,        0,          0, false,      false,     false,           0,        0, false     },
	{      2, ObjectGraphic::L1BRAZ,    0,       0, DunType::town,      THEME_NONE,              -1,                 0,          0,        0,          0, false,      false,     false,           0,        0, false     },
	{      2, ObjectGraphic::L1BRAZ,    0,       0, DunType::town,      THEME_NONE,              -1,                 0,          0,        0,          0, false,      false,     false,           0,        0, false     },
	{      2, ObjectGraphic::CRUXSK1,   0,       0, DunType::town,      THEME_NONE,              -1,                 0,          1,       15,         96, true,       false,     true,            1,        3, false     },
	{      2, ObjectGraphic::CRUXSK2,   0,       0, DunType::town,      THEME_NONE,              -1,                 0,          1,       15,         96, true,       false,     true,            1,        3, false     },
	{      2, ObjectGraphic::CRUXSK3,   0,       0, DunType::town,      THEME_NONE,              -1,                 0,          1,       15,         96, true,       false,     true,            1,        3, false     },
	{      1, ObjectGraphic::ROCKSTAN,  5,       5, DunType::town,      THEME_NONE,              -1,                 0,          1,        0,         96, true,       true,      true,            0,        0, false     },
	{      2, ObjectGraphic::ANGEL,     0,       0, DunType::town,      THEME_NONE,              -1,                 0,          1,        0,         96, true,       false,     true,            0,        0, false     },
	{      2, ObjectGraphic::BOOK2,     0,       0, DunType::town,      THEME_NONE,              -1,                 0,          1,        0,         96, true,       true,      true,            0,        3, false     },
	{      2, ObjectGraphic::BURNCROS,  0,       0, DunType::town,      THEME_NONE,              -1,                 1,          0,       10,        160, true,       false,     false,           0,        0, false     },
	{      2, ObjectGraphic::NUDE2,     0,       0, DunType::town,      THEME_NONE,              -1,                 1,          3,        6,        128, true,       false,     true,            0,        0, false     },
	{      1, ObjectGraphic::SWITCH4,  16,      16, DunType::town,      THEME_NONE,              -1,                 0,          1,        0,         96, true,       true,      true,            0,        1, true      },
	{      1, ObjectGraphic::TNUDEM,   13,      16, DunType::town,      THEME_NONE,              Q_BUTCHER,          0,          1,        0,        128, true,       false,     true,            0,        0, false     },
	{      1, ObjectGraphic::TNUDEM,   13,      16, DunType::town,      THEME_TORTURE,           Q_BUTCHER,          0,          2,        0,        128, true,       false,     true,            0,        0, false     },
	{      1, ObjectGraphic::TNUDEM,   13,      16, DunType::town,      THEME_TORTURE,           Q_BUTCHER,          0,          3,        0,        128, true,       false,     true,            0,        0, false     },
	{      1, ObjectGraphic::TNUDEM,   13,      16, DunType::town,      THEME_TORTURE,           Q_BUTCHER,          0,          4,        0,        128, true,       false,     true,            0,        0, false     },
	{      1, ObjectGraphic::TNUDEW,   13,      16, DunType::town,      THEME_TORTURE,           Q_BUTCHER,          0,          1,        0,        128, true,       false,     true,            0,        0, false     },
	{      1, ObjectGraphic::TNUDEW,   13,      16, DunType::town,      THEME_TORTURE,           Q_BUTCHER,          0,          2,        0,        128, true,       false,     true,            0,        0, false     },
	{      1, ObjectGraphic::TNUDEW,   13,      16, DunType::town,      THEME_TORTURE,           Q_BUTCHER,          0,          3,        0,        128, true,       false,     true,            0,        0, false     },
	{      1, ObjectGraphic::TSOUL,    13,      16, DunType::town,      THEME_NONE,              Q_BUTCHER,          0,          1,        0,        128, true,       false,     true,            0,        0, false     },
	{      1, ObjectGraphic::TSOUL,    13,      16, DunType::town,      THEME_NONE,              Q_BUTCHER,          0,          2,        0,        128, true,       false,     true,            0,        0, false     },
	{      1, ObjectGraphic::TSOUL,    13,      16, DunType::town,      THEME_NONE,              Q_BUTCHER,          0,          3,        0,        128, true,       false,     true,            0,        0, false     },
	{      1, ObjectGraphic::TSOUL,    13,      16, DunType::town,      THEME_NONE,              Q_BUTCHER,          0,          4,        0,        128, true,       false,     true,            0,        0, false     },
	{      1, ObjectGraphic::TSOUL,    13,      16, DunType::town,      THEME_NONE,              Q_BUTCHER,          0,          5,        0,        128, true,       false,     true,            0,        0, false     },
	{      1, ObjectGraphic::BOOK2,     6,       6, DunType::town,      THEME_NONE,              -1,                 0,          4,        0,         96, true,       true,      true,            0,        3, false     },
	{      1, ObjectGraphic::L2DOORS,   5,       8, DunType::catacombs, THEME_NONE,              -1,                 0,          1,        0,         64, false,      false,     true,            0,        3, true      },
	{      1, ObjectGraphic::L2DOORS,   5,       8, DunType::catacombs, THEME_NONE,              -1,                 0,          2,        0,         64, false,      false,     true,            0,        3, false     },
	{      1, ObjectGraphic::WTORCH4,   5,       8, DunType::catacombs, THEME_NONE,              -1,                 1,          1,        9,         96, false,      true,      false,           0,        0, false     },
	{      1, ObjectGraphic::WTORCH3,   5,       8, DunType::catacombs, THEME_NONE,              -1,                 1,          1,        9,         96, false,      true,      false,           0,        0, false     },
	{      1, ObjectGraphic::WTORCH1,   5,       8, DunType::catacombs, THEME_NONE,              -1,                 1,          1,        9,         96, false,      true,      false,           0,        0, false     },
	{      1, ObjectGraphic::WTORCH2,   5,       8, DunType::catacombs, THEME_NONE,              -1,                 1,          1,        9,         96, false,      true,      false,           0,        0, false     },
	{      1, ObjectGraphic::SARC,      1,       4, DunType::cathedral, THEME_NONE,              -1,                 0,          1,        5,        128, true,       true,      true,            0,        3, true      },
	{      2, ObjectGraphic::FLAME1,    1,       4, DunType::cathedral, THEME_NONE,              -1,                 0,          1,       20,         96, false,      true,      true,            0,        0, false     },
	{      2, ObjectGraphic::LEVER,     1,       4, DunType::cathedral, THEME_NONE,              -1,                 0,          1,        2,         96, true,       true,      true,            0,        1, true      },
	{      2, ObjectGraphic::MINIWATR,  1,       4, DunType::cathedral, THEME_NONE,              -1,                 1,          1,       10,         64, true,       false,     true,            0,        0, false     },
	{      1, ObjectGraphic::BOOK1,     3,       4, DunType::cathedral, THEME_NONE,              -1,                 0,          1,        0,         96, true,       true,      true,            0,        3, false     },
	{      1, ObjectGraphic::TRAPHOLE,  1,      16, DunType::town,      THEME_NONE,              -1,                 0,          1,        0,         64, false,      true,      true,            0,        0, false     },
	{      1, ObjectGraphic::TRAPHOLE,  1,      16, DunType::town,      THEME_NONE,              -1,                 0,          2,        0,         64, false,      true,      true,            0,        0, false     },
	{      2, ObjectGraphic::BCASE,     0,       0, DunType::town,      THEME_NONE,              -1,                 0,          1,        0,         96, true,       false,     true,            0,        0, false     },
	{      2, ObjectGraphic::WEAPSTND,  0,       0, DunType::town,      THEME_NONE,              -1,                 0,          1,        0,         96, true,       false,     true,            0,        0, false     },
	{      1, ObjectGraphic::BARREL,    1,      16, DunType::town,      THEME_NONE,              -1,                 0,          1,        9,         96, true,       true,      true,            1,        3, false     },
	{      1, ObjectGraphic::BARRELEX,  1,      16, DunType::town,      THEME_NONE,              -1,                 0,          1,       10,         96, true,       true,      true,            1,        3, false     },
	{      3, ObjectGraphic::LSHRINEG,  0,       0, DunType::town,      THEME_SHRINE,            -1,                 0,          1,       11,        128, false,      false,     true,            0,        3, false     },
	{      3, ObjectGraphic::RSHRINEG,  0,       0, DunType::town,      THEME_SHRINE,            -1,                 0,          1,       11,        128, false,      false,     true,            0,        3, false     },
	{      3, ObjectGraphic::BOOK2,     0,       0, DunType::town,      THEME_SKELROOM,          -1,                 0,          4,        0,         96, true,       true,      true,            0,        3, false     },
	{      3, ObjectGraphic::BCASE,     0,       0, DunType::town,      THEME_LIBRARY,           -1,                 0,          3,        0,         96, false,      false,     true,            0,        3, false     },
	{      3, ObjectGraphic::BCASE,     0,       0, DunType::town,      THEME_LIBRARY,           -1,                 0,          4,        0,         96, false,      false,     true,            0,        3, false     },
	{      3, ObjectGraphic::BOOK2,     0,       0, DunType::town,      THEME_LIBRARY,           -1,                 0,          1,        0,         96, true,       true,      true,            0,        3, false     },
	{      3, ObjectGraphic::CANDLE2,   0,       0, DunType::town,      THEME_LIBRARY,           -1,                 1,          2,        4,         96, true,       true,      true,            0,        0, false     },
	{      3, ObjectGraphic::BLOODFNT,  0,       0, DunType::town,      THEME_BLOODFOUNTAIN,     -1,                 1,          2,       10,         96, true,       true,      true,            0,        3, false     },
	{      1, ObjectGraphic::DECAP,    13,      16, DunType::town,      THEME_DECAPITATED,       -1,                 0,          1,        0,         96, true,       true,      true,            0,        1, false     },
	{      1, ObjectGraphic::CHEST1,    1,      16, DunType::town,      THEME_NONE,              -1,                 0,          1,        0,         96, true,       true,      true,            0,        1, true      },
	{      1, ObjectGraphic::CHEST2,    1,      16, DunType::town,      THEME_NONE,              -1,                 0,          1,        0,         96, true,       true,      true,            0,        1, true      },
	{      1, ObjectGraphic::CHEST3,    1,      16, DunType::town,      THEME_NONE,              -1,                 0,          1,        0,         96, true,       true,      true,            0,        1, true      },
	{      1, ObjectGraphic::BOOK1,     7,       7, DunType::catacombs, THEME_NONE,              Q_BLIND,            0,          1,        0,         96, true,       true,      true,            0,        3, false     },
	{      1, ObjectGraphic::BOOK1,     5,       5, DunType::catacombs, THEME_NONE,              Q_BLOOD,            0,          4,        0,         96, true,       true,      true,            0,        3, false     },
	{      1, ObjectGraphic::PEDISTL,   5,       5, DunType::catacombs, THEME_NONE,              Q_BLOOD,            0,          1,        0,         96, true,       true,      true,            0,        3, false     },
	{      1, ObjectGraphic::L3DOORS,   9,      12, DunType::caves,     THEME_NONE,              -1,                 0,          1,        0,         64, false,      false,     true,            0,        3, true      },
	{      1, ObjectGraphic::L3DOORS,   9,      12, DunType::caves,     THEME_NONE,              -1,                 0,          2,        0,         64, false,      false,     true,            0,        3, true      },
	{      3, ObjectGraphic::PFOUNTN,   0,       0, DunType::town,      THEME_PURIFYINGFOUNTAIN, -1,                 1,          2,       10,        128, true,       true,      true,            0,        3, false     },
	{      3, ObjectGraphic::ARMSTAND,  0,       0, DunType::town,      THEME_ARMORSTAND,        -1,                 0,          1,        0,         96, true,       false,     true,            0,        3, false     },
	{      3, ObjectGraphic::ARMSTAND,  0,       0, DunType::town,      THEME_ARMORSTAND,        -1,                 0,          2,        0,         96, true,       false,     true,            0,        0, false     },
	{      3, ObjectGraphic::GOATSHRN,  0,       0, DunType::town,      THEME_GOATSHRINE,        -1,                 1,          2,       10,         96, true,       true,      true,            0,        3, false     },
	{      1, ObjectGraphic::CAULDREN, 13,      16, DunType::town,      THEME_NONE,              -1,                 0,          1,        0,         96, true,       false,     true,            0,        3, false     },
	{      3, ObjectGraphic::MFOUNTN,   0,       0, DunType::town,      THEME_MURKYFOUNTAIN,     -1,                 1,          2,       10,        128, true,       true,      true,            0,        3, false     },
	{      3, ObjectGraphic::TFOUNTN,   0,       0, DunType::town,      THEME_TEARFOUNTAIN,      -1,                 1,          2,        4,        128, true,       true,      true,            0,        3, false     },
	{      1, ObjectGraphic::ALTBOY,    0,       0, DunType::cathedral, THEME_NONE,              Q_BETRAYER,         0,          1,        0,        128, true,       true,      true,            0,        0, false     },
	{      1, ObjectGraphic::MCIRL,     0,       0, DunType::cathedral, THEME_NONE,              Q_BETRAYER,         0,          1,        0,         96, false,      true,      true,            0,        0, false     },
	{      1, ObjectGraphic::MCIRL,     0,       0, DunType::cathedral, THEME_NONE,              Q_BETRAYER,         0,          1,        0,         96, false,      true,      true,            0,        0, false     },
	{      1, ObjectGraphic::BKSLBRNT,  4,      12, DunType::town,      THEME_NONE,              -1,                 0,          1,        0,         96, true,       true,      true,            0,        3, false     },
	{      1, ObjectGraphic::CANDLE2,   2,      12, DunType::town,      THEME_NONE,              Q_BETRAYER,         1,          2,        4,         96, true,       true,      true,            0,        0, false     },
	{      1, ObjectGraphic::BOOK1,    13,      13, DunType::hell,      THEME_NONE,              Q_WARLORD,          0,          4,        0,         96, true,       true,      true,            0,        3, false     },
	{      1, ObjectGraphic::ARMSTAND, 13,      13, DunType::town,      THEME_NONE,              Q_WARLORD,          0,          1,        0,         96, true,       false,     true,            0,        3, false     },
	{      2, ObjectGraphic::WEAPSTND, 13,      13, DunType::town,      THEME_NONE,              Q_WARLORD,          0,          1,        0,         96, true,       false,     true,            0,        3, false     },
	{      2, ObjectGraphic::BURNCROS,  0,       0, DunType::town,      THEME_BRNCROSS,          -1,                 1,          0,       10,        160, true,       false,     false,           0,        0, false     },
	{      2, ObjectGraphic::WEAPSTND,  0,       0, DunType::town,      THEME_WEAPONRACK,        -1,                 0,          1,        0,         96, true,       false,     true,            0,        3, false     },
	{      2, ObjectGraphic::WEAPSTND,  0,       0, DunType::town,      THEME_WEAPONRACK,        -1,                 0,          2,        0,         96, true,       false,     true,            0,        0, false     },
	{      2, ObjectGraphic::MUSHPTCH,  0,       0, DunType::town,      THEME_NONE,              Q_MUSHROOM,         0,          1,        0,         96, true,       true,      true,            0,        3, true      },
	{      2, ObjectGraphic::LZSTAND,   0,       0, DunType::town,      THEME_NONE,              Q_BETRAYER,         0,          1,        0,        128, true,       false,     true,            0,        3, false     },
	{      1, ObjectGraphic::DECAP,     9,       9, DunType::caves,     THEME_NONE,              -1,                 0,          2,        0,         96, true,       true,      true,            0,        1, false     },
	{      2, ObjectGraphic::CHEST3,    0,       0, DunType::town,      THEME_NONE,              -1,                 0,          1,        0,         96, true,       true,      true,            0,        1, true      },
	{     -1, 0,               0,       0, DunType::none,      THEME_NONE,              -1,                 0,          0,        0,          0, false,      false,     false,           0,        0, false     }
	// clang-format on
};

/** Maps from object_graphic_id to object CEL name. */
char *ObjMasterLoadList[56] = { // might be const
	"L1Braz",
	"L1Doors",
	"Lever",
	"Chest1",
	"Chest2",
	"Banner",
	"SkulPile",
	"SkulFire",
	"SkulStik",
	"CruxSk1",
	"CruxSk2",
	"CruxSk3",
	"Book1",
	"Book2",
	"Rockstan",
	"Angel",
	"Chest3",
	"Burncros",
	"Candle2",
	"Nude2",
	"Switch4",
	"TNudeM",
	"TNudeW",
	"TSoul",
	"L2Doors",
	"WTorch4",
	"WTorch3",
	"Sarc",
	"Flame1",
	"Prsrplt1",
	"Traphole",
	"MiniWatr",
	"WTorch2",
	"WTorch1",
	"BCase",
	"BShelf",
	"WeapStnd",
	"Barrel",
	"Barrelex",
	"LShrineG",
	"RShrineG",
	"Bloodfnt",
	"Decap",
	"Pedistl",
	"L3Doors",
	"PFountn",
	"Armstand",
	"Goatshrn",
	"Cauldren",
	"MFountn",
	"TFountn",
	"Altboy",
	"Mcirl",
	"Bkslbrnt",
	"Mushptch",
	"LzStand"
};

DEVILUTION_END_NAMESPACE
