// HEADER_GOES_HERE
#ifndef __TOWNER_DEFS_H__
#define __TOWNER_DEFS_H__

DEVILUTION_BEGIN_NAMESPACE


typedef enum talk_id {
	STORE_NONE = 0x0,
	STORE_SMITH = 0x1,
	STORE_SBUY = 0x2,
	STORE_SSELL = 0x3,
	STORE_SREPAIR = 0x4,
	STORE_WITCH = 0x5,
	STORE_WBUY = 0x6,
	STORE_WSELL = 0x7,
	STORE_WRECHARGE = 0x8,
	STORE_NOMONEY = 0x9,
	STORE_NOROOM = 0xA,
	STORE_CONFIRM = 0xB,
	STORE_BOY = 0xC,
	STORE_BBOY = 0xD,
	STORE_HEALER = 0xE,
	STORE_STORY = 0xF,
	STORE_HBUY = 0x10,
	STORE_SIDENTIFY = 0x11,
	STORE_SPBUY = 0x12,
	STORE_GOSSIP = 0x13,
	STORE_IDSHOW = 0x14,
	STORE_TAVERN = 0x15,
	STORE_DRUNK = 0x16,
	STORE_BARMAID = 0x17,
} talk_id;

typedef enum _talker_id {
	TOWN_SMITH = 0x0,
	TOWN_HEALER = 0x1,
	TOWN_DEADGUY = 0x2,
	TOWN_TAVERN = 0x3,
	TOWN_STORY = 0x4,
	TOWN_DRUNK = 0x5,
	TOWN_WITCH = 0x6,
	TOWN_BMAID = 0x7,
	TOWN_PEGBOY = 0x8,
	TOWN_COW = 0x9,
	TOWN_PRIEST = 0xA,
} _talker_id;


DEVILUTION_END_NAMESPACE

#endif /* __TOWNER_DEFS_H__ */
